### ISSUE TITLE
Signature verification always succeeds

### ISSUE THREAD

**Issue by xotatera** [Argyle-Software/sphincsplus#7]
I couldn't get the signature verification to fail.
Signatures signed with one pair can be verified with literally any other pair and it succeeds every time.
Is this actually in an unfinished/unusable state as of yet?

**Comment by mberry** [comment]
This has been fixed, signatures weren't affected but verification was.

> Is this actually in an unfinished/unusable state as of yet?

 It's in a working state but there's still a lot to do before stabilisation and only so much time for open source software, are you interested becoming a contributor?
